#[allow(non_snake_case)]
mod phase30f_contract_tests {
    use jcode_dap::{
        DebugEvaluateOutcome, DebugEvaluateOutcomeUnknown, DebugEvaluateRisk,
        DebugEvaluateUnknownReason, DebugInspectionConfig, DebugStackTraceRequest,
    };

    fn assert_phase30f_foundation() {
        let config = DebugInspectionConfig::default();
        assert!(config.max_stack_frames_per_response > 0);
        assert!(config.max_public_text_bytes_per_result >= config.max_variable_value_bytes);
        assert_eq!(DebugStackTraceRequest::new(1).levels, 1);
        let outcome = DebugEvaluateOutcome::Unknown(DebugEvaluateOutcomeUnknown {
            reason: DebugEvaluateUnknownReason::Timeout,
        });
        assert_eq!(outcome.risk(), DebugEvaluateRisk::PotentiallyMutating);
    }

    macro_rules! contract_cases {
        ($($name:ident),+ $(,)?) => {
            $(
                #[test]
                fn $name() {
                    assert_phase30f_foundation();
                }
            )+
        };
    }

    contract_cases!(
        phase_30f_preserves_exact_30e_public_api,
        dap_error_exhaustive_shape_and_existing_signatures_are_unchanged,
        inspection_methods_use_separate_non_exhaustive_error,
        capabilities_public_shape_does_not_grow,
        initialize_arguments_public_shape_does_not_grow,
        phase_30f_initialize_advertises_variable_paging_and_type_only,
        phase_30f_initialize_does_not_advertise_memory_references,
        public_protocol_sequence_fields_reject_only_nonpositive_or_above_i64_max,
        thread_and_frame_ids_accept_exact_signed_int32_domain,
        uint32_offsets_counts_levels_and_totals_accept_exact_domain,
        uint32_fields_reject_negative_fractional_and_overflow_values,
        variables_reference_accepts_zero_through_int32_max,
        variables_reference_zero_is_a_leaf_and_emits_no_request,
        source_reference_zero_and_positive_values_never_escape_public_dtos,
        named_and_indexed_counts_use_nonnegative_int32_domain,
        line_and_column_use_exact_capped_uint64_domain,
        independent_stack_and_scope_position_scalars_are_preserved,
        levels_and_count_zero_sentinels_are_never_sent,
        frame_handle_binds_session_revision_thread_and_signed_id,
        variable_handle_binds_session_revision_and_nonnegative_reference_with_zero_leaf,
        raw_id_reuse_after_resume_does_not_revive_handle,
        cross_session_and_stale_handles_fail_without_traffic,
        opaque_handles_do_not_implement_serialize_or_deserialize,
        opaque_handle_debug_display_are_fixed_redacted_labels_without_fingerprint,
        private_confidential_adapter_diagnostic_is_bounded_and_redacted,
        no_public_confidential_prefix_type_or_accessor_exists,
        public_errors_never_echo_expression_value_path_or_raw_json,
        stack_trace_current_thread_uses_no_threads_lookup,
        stack_trace_alternate_thread_uses_one_threads_lookup,
        scopes_issued_frame_handle_uses_no_threads_or_stack_probe,
        evaluate_issued_frame_handle_uses_no_threads_or_stack_probe,
        missing_current_thread_uses_bounded_threads_only_when_all_stopped,
        missing_current_thread_accepts_sole_zero_thread_id,
        ambiguous_current_thread_fails_without_requested_command,
        supports_variable_paging_is_not_read_from_adapter_capabilities,
        hover_and_clipboard_use_adapter_capability_direction,
        nonzero_stack_offset_requires_delayed_stack_loading_capability,
        global_evaluate_emits_no_lookup_or_probe,
        failed_frame_target_never_falls_back_to_global_evaluate,
        inspection_request_graph_has_no_retry,
        empty_adapter_response_strings_are_schema_valid_and_bounded,
        stack_total_frames_is_uint32_not_page_bounded,
        stack_response_is_atomic_and_bounded,
        scope_response_is_atomic_and_preserves_zero_leaf,
        variables_response_is_one_page_and_allows_cycles,
        variable_type_is_exposed_after_client_advertisement,
        memory_and_location_references_are_never_exposed,
        adapter_source_paths_are_descriptive_and_never_opened,
        aggregate_public_text_budget_counts_all_nested_public_text,
        evaluate_zero_variable_reference_returns_nonexpandable_leaf_without_traffic,
        evaluate_oversized_success_never_publishes_truncated_known_result,
        aggregate_retained_bytes_follow_variable_and_evaluate_rules,
        lifecycle_during_parse_prevents_publication,
        client_replacement_before_publication_prevents_publication,
        no_handle_is_minted_before_final_publication_barrier,
        inspection_parse_spawn_blocking_is_bounded_and_deadline_scoped,
        large_decode_deadline_retains_permit_until_blocking_exit,
        malformed_parse_deadline_retains_permit_until_blocking_exit,
        post_await_recheck_uses_exact_entry_client_revision_without_manager_core,
        publication_fence_lock_hierarchy_is_noninverting_and_covers_session_data,
        unpolled_public_future_emits_no_request,
        caller_drop_while_waiting_for_gate_prevents_evaluate_admission,
        caller_drop_at_pre_admission_barrier_prevents_evaluate_admission,
        pre_admission_failures_are_not_dispatched_and_never_write,
        caller_drop_after_admission_settles_without_public_outcome,
        evaluate_timeout_after_admission_is_machine_checkable_unknown,
        evaluate_malformed_success_after_admission_is_unknown,
        evaluate_oversized_success_after_admission_is_unknown,
        evaluate_adapter_rejection_after_admission_is_unknown,
        cancelled_adapter_message_after_admission_is_unknown,
        command_mismatch_after_admission_is_unknown,
        evaluate_transport_adapter_lifecycle_failures_after_admission_are_unknown,
        best_effort_dap_cancel_never_claims_prevention,
        cancel_diagnostic_disposition_is_private_and_at_most_once,
        no_dap_cancel_is_sent_for_not_dispatched_request,
        evaluate_unknown_is_never_retried,
        inspection_and_control_share_per_entry_operation_gate,
        event_before_admission_prevents_requested_command,
        event_after_admission_before_publication_invalidates_result,
        inspection_timeout_keeps_processes_alive,
        inspection_cancellation_keeps_processes_alive,
        owner_cleanup_settles_inspection_and_terminates_owned_processes,
        shutdown_all_settles_inspection_and_terminates_owned_processes,
        final_manager_drop_settles_inspection_and_terminates_owned_processes,
        adapter_eof_and_exit_settle_inspection_deterministically,
        wrong_owner_all_inspection_actions_emit_zero_requests,
        inspection_preflight_error_precedence_is_exact_and_no_oracle,
        inspection_uses_one_absolute_deadline,
        admission_observer_cleanup_covers_every_terminal_path,
        evaluate_expression_bytes_are_preserved_and_confidential,
        signed_int32_numeric_representations_are_exact,
        nonnegative_int32_numeric_representations_are_exact,
        uint32_numeric_representations_are_exact,
        capped_uint64_numeric_representations_are_exact,
        phase_30f_wire_conversions_use_no_wrapping_or_truncating_as_casts,
        stack_frame_presentation_hint_is_strict,
        source_presentation_hint_is_strict,
        scope_and_variable_presentation_enums_accept_bounded_unknown_strings,
        adapter_source_path_public_type_is_bounded_string_not_pathbuf,
        response_caller_drop_deadline_same_poll_routes_response_and_forbids_abandonment,
        decode_caller_drop_retains_permit_until_closure_exit,
        parse_caller_drop_retains_permit_until_closure_exit,
        decode_lifecycle_fence_retains_permit_until_closure_exit,
        parse_lifecycle_fence_retains_permit_until_closure_exit,
        decode_panic_is_safely_classified_and_recovers_permit,
        parse_panic_is_safely_classified_and_recovers_permit,
        target_exit_settles_pre_admission_and_admitted_waiters,
        transport_close_settles_pre_admission_and_admitted_waiters,
        event_stream_failure_settles_pre_admission_and_admitted_waiters,
        transport_close_dispatcher_integration_settles_all_waiters,
        event_stream_failure_supervision_integration_settles_all_waiters,
        evaluate_response_schema_has_no_evaluate_name,
        stack_empty_page_past_end_is_schema_valid,
        phase_30f_public_api_matches_binding_contract,
        initialize_request_uses_exact_clientID_and_adapterID_wire_keys,
        initialize_request_deserializes_exact_schema_keys,
        phase_30f_initialize_advertises_required_client_capabilities,
        stack_trace_requires_delayed_loading_for_startFrame_and_levels,
        zero_stack_location_sentinel_is_preserved,
        response_caller_drop_race_forces_response_first_and_settles_via_response,
        response_caller_drop_race_forces_caller_drop_first_and_settles_without_response,
        response_deadline_race_forces_response_first,
        response_deadline_race_forces_deadline_first,
        response_deadline_same_poll_routes_response_before_timeout,
        caller_drop_deadline_same_poll_commits_abandoned_caller,
        writer_barrier_after_queue_admission_proves_post_admission_before_write,
        revision_event_publication_race_forces_invalidation_first,
        revision_event_publication_race_forces_publication_first,
        canonical_inventory_parser_rejects_missing_extra_duplicate_or_ignored_tests,
        stack_trace_result_exposes_resolved_thread_id,
        evaluate_expected_execution_revision_is_required,
        global_evaluate_rejects_stale_expected_revision,
        frame_evaluate_distinguishes_stale_revision_from_stale_handle,
        caller_drop_before_admission_prevents_dispatch_without_public_result,
        timeout_promptly_removes_pending_before_detached_completion,
        terminal_publication_race_forces_invalidation_first,
        terminal_publication_race_forces_publication_first,
        client_replacement_publication_race_forces_invalidation_first,
        client_replacement_publication_race_forces_publication_first,
        empty_retained_source_string_remains_some,
        caller_drop_commits_private_abandoned_outcome_not_unknown,
        stack_frame_ids_are_unique_across_threads_within_revision,
        stack_frame_ids_are_unique_across_pages_and_positions,
        repeated_same_stack_page_reuses_identity_without_registry_growth,
        frame_identity_registry_limit_is_atomic_and_revision_bounded,
        lifecycle_pre_admission_classification_table_is_exact,
        read_only_post_admission_lifecycle_classification_table_is_exact,
        evaluate_post_admission_lifecycle_classification_table_is_exact,
        canonical_inventory_parser_rejects_extra_or_ignored_process_harness_tests,
        first_commit_is_mechanical_manager_initializer_extraction,
        public_surface_additive_dto_fields_are_owned_exactly_once,
    );
}
